apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todos-fullstack
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Jerrybaijy/todos-react-flask-mysql-fullstack.git
    targetRevision: HEAD
    path: dev # 指向配置所在的 dev 路径

  destination:
    server: https://kubernetes.default.svc
    namespace: todos-fullstack

  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true